# Generated by Django 4.2.7 on 2023-11-19 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
        ('study_sets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyterm',
            name='back_audio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='back_audio_study_term', to='uploads.audiofile'),
        ),
        migrations.AlterField(
            model_name='studyterm',
            name='back_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='back_image_study_term', to='uploads.imagefile'),
        ),
        migrations.AlterField(
            model_name='studyterm',
            name='front_audio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='front_audio_study_term', to='uploads.audiofile'),
        ),
        migrations.AlterField(
            model_name='studyterm',
            name='front_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='front_image_study_term', to='uploads.imagefile'),
        ),
        migrations.DeleteModel(
            name='AudioFile',
        ),
        migrations.DeleteModel(
            name='ImageFile',
        ),
    ]
