# Generated by Django 4.2.7 on 2023-12-29 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_texttospeechaudio'),
        ('study_sets', '0004_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyterm',
            name='back_tts_audio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='back_tts_study_term', to='uploads.texttospeechaudio'),
        ),
        migrations.AddField(
            model_name='studyterm',
            name='back_voice_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studyterm',
            name='front_tts_audio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='front_tts_study_term', to='uploads.texttospeechaudio'),
        ),
        migrations.AddField(
            model_name='studyterm',
            name='front_voice_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
