# Generated by Django 4.2.7 on 2023-12-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_sets', '0005_studyterm_back_tts_audio_studyterm_back_voice_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyterm',
            name='back_voice_id',
            field=models.CharField(default='Joanna', max_length=100),
        ),
        migrations.AlterField(
            model_name='studyterm',
            name='front_voice_id',
            field=models.CharField(default='Joanna', max_length=100),
        ),
    ]
