# Generated by Django 4.2.7 on 2024-01-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_sets', '0007_studyterm_sort_order_alter_studyterm_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyterm',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
