# Generated by Django 4.2.7 on 2023-11-19 17:50

from django.db import migrations, models
import uploads.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='file_path',
            field=models.FileField(max_length=200, upload_to=uploads.models.get_audio_path),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='file_path',
            field=models.ImageField(max_length=200, upload_to=uploads.models.get_image_path),
        ),
    ]
