# Generated by Django 4.2.7 on 2023-11-21 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploads', '0002_alter_audiofile_file_path_alter_imagefile_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='uploader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_audio_files', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagefile',
            name='uploader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_image_files', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
