# Generated by Django 4.2.7 on 2023-12-29 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uploads.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploads', '0003_audiofile_uploader_imagefile_uploader'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextToSpeechAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to=uploads.models.get_tts_audio_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_to_speech_audios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
