# Generated by Django 4.2.7 on 2023-12-29 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_texttospeechaudio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiofile',
            old_name='file_path',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='imagefile',
            old_name='file_path',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='texttospeechaudio',
            old_name='audio_file',
            new_name='file',
        ),
    ]
