# Generated by Django 4.2.7 on 2023-11-16 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AudioFile",
            fields=[
                (
                    "pk_audio_file_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("file_path", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ImageFile",
            fields=[
                (
                    "pk_image_file_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("file_path", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="StudySet",
            fields=[
                (
                    "pk_study_set_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("set_title", models.CharField(max_length=64)),
                ("set_description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="StudyTerm",
            fields=[
                ("pk_term_id", models.AutoField(primary_key=True, serialize=False)),
                ("front_text", models.TextField(blank=True, default="Front")),
                ("back_text", models.TextField(blank=True, default="Back")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fk_back_audio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="back_audio_terms",
                        to="study_set.audiofile",
                    ),
                ),
                (
                    "fk_back_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="back_terms",
                        to="study_set.imagefile",
                    ),
                ),
                (
                    "fk_front_audio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="front_audio_terms",
                        to="study_set.audiofile",
                    ),
                ),
                (
                    "fk_front_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="front_terms",
                        to="study_set.imagefile",
                    ),
                ),
                (
                    "study_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_terms",
                        to="study_set.studyset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("pk_tag_id", models.AutoField(primary_key=True, serialize=False)),
                ("tag_name", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="StudyTermTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "study_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="study_set.studyterm",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="study_set.tag"
                    ),
                ),
            ],
        ),
    ]
