# Generated by Django 4.2.7 on 2023-12-20 07:03

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=25, unique=True, validators=[users.models.validate_no_whitespace]),
        ),
    ]
