# Generated by Django 4.2.7 on 2023-12-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usermodel_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
